name: Terraform Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Terraform-Checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  # No need to specify version explicitly, uses latest by default
        uses: actions/checkout@v3  # This action is actually no longer deprecated

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3  # Already updated correctly

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check


    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
    
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact